language: node_js
node_js:
- '4.2'
sudo: required
dist: trusty
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y clang-3.4
- git clone https://github.com/kripken/emscripten.git
- cd emscripten && git checkout 1.26.0; cd -
before_script:
- export PATH=`pwd`/emscripten/:$PATH
- export EMCC_FAST_COMPILER=0
- emcc
deploy:
  provider: npm
  skip_cleanup: true
  email: jononor@gmail.com
  api_key:
    secure: hfh6iQJGxbxjWx1ySF6XsRfkXsvlusS8rf5JD3YZRlTQp/PSMpXmVqMwwjkgE53sn9TagXyeDcfbKoqQLNU1P1lwC4TM6dD6OeoSlWByWIiZwjoIJHcqkfWdCM01fMWgjxMNGNkfF/3cyBoRHzBuvH3pNlIWBNvB2aC0bM8C3dM=
  on:
    tags: true
    repo: microflo/microflo-emscripten
